### ISSUE TITLE
ListPlaceholder should show spinner for both `undefined` and `null`

### ISSUE THREAD

**Issue by adhipg** [grommet/grommet-addons#10]
`ListPlaceholder` only shows a spinner when the `filteredTotal` is explicitly `undefined` (https://github.com/grommet/grommet-addons/blob/master/src/js/components/ListPlaceholder.js#L17).

In certain scenarios (eg when we refetch data from the server and invalidate current data), we will want to reset the value of the `filteredTotal` while we wait again. I believe it's way easier to contemplate setting the value to `null` rather than `undefined` (assigning a variable to be `undefined` always seemed icky to me)

**Comment by cherih** [comment]
Fixed this and committed it. Created PR #11 and am waiting for it to be merged.
