### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by atanasster** [grommet/grommet-addons#15]
Seems the npm package is not updated (and its a bit confusing, since it also says "0.4.0"

**Comment by alansouzati** [comment]
yeah it's been while since we did a release for `grommet-addons`. The release numbers are different than the Grommet core. So 0.4.0 is in fact the latest release. Let me work on releasing a new version for Grommet addons.

**Comment by atanasster** [comment]
np, was just letting you know, I am installing from https://github.com/grommet/grommet-addons/tarball/stable

**Comment by alansouzati** [comment]
https://github.com/grommet/grommet-addons/releases/tag/v0.5.0

**Comment by alansouzati** [comment]
Yeah stable is always going to point to the lastest version. Stable is just a shortcut to use the latest features. If you installed it, you should always be up to date.
